---
- name: install nginx
  apt: pkg=nginx state=present
- name: delete nginx default virtualhost
  file: path=/etc/nginx/{{ item }}/default state=absent
  notify: restart nginx
  with_items:
  - sites-available
  - sites-enabled
- name: copy nginx.conf
  template: dest=/etc/nginx/nginx.conf src=nginx.conf.j2
  notify: restart nginx
- name: copy mime.types
  copy: dest=/etc/nginx/mime.types src=mime.types
  notify: restart nginx
