---
- name: install php packages
  apt: pkg={{ item }} state=present
  with_items:
  - php5-cli
  - php5-curl
  - php5-fpm
  - php5-intl
- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php chdir=/usr/local/bin creates=/usr/local/bin/composer.phar
